# Generated by Django 6.0.5 on 2026-06-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('producto', models.CharField(choices=[('stockwise', 'StockWise'), ('stockmenu', 'StockMenu')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('instantly_campaign_id', models.CharField(blank=True, max_length=200)),
                ('tono', models.CharField(choices=[('directo', 'Directo y al grano'), ('consultivo', 'Consultivo'), ('curioso', 'Curioso/pregunta')], default='directo', max_length=20)),
                ('num_followups', models.IntegerField(default=2)),
                ('total_prospectos', models.IntegerField(default=0)),
                ('emails_generados', models.IntegerField(default=0)),
                ('emails_enviados', models.IntegerField(default=0)),
                ('respuestas', models.IntegerField(default=0)),
                ('interesados', models.IntegerField(default=0)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('industria', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('tamano_empresa', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('email_generado', 'Email generado'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado a Instantly'), ('respondio', 'Respondió'), ('interesado', 'Interesado'), ('no_interesado', 'No interesado'), ('descartado', 'Descartado')], default='pendiente', max_length=30)),
                ('instantly_lead_id', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectos', to='campaigns.campana')),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'unique_together': {('campana', 'email')},
            },
        ),
        migrations.CreateModel(
            name='EmailGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('tokens_usados', models.IntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('enviado_a_instantly', models.BooleanField(default=False)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('editado_en', models.DateTimeField(auto_now=True)),
                ('prospecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_generado', to='campaigns.prospecto')),
            ],
            options={
                'verbose_name': 'Email generado',
                'verbose_name_plural': 'Emails generados',
            },
        ),
        migrations.CreateModel(
            name='ProspectoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxima_accion', models.CharField(choices=[('agendar_demo', 'Agendar demo'), ('enviar_info', 'Enviar más info'), ('llamar', 'Llamar'), ('seguimiento', 'Seguimiento'), ('cerrado', 'Cerrado - cliente')], default='agendar_demo', max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('prospecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.prospecto')),
            ],
            options={
                'verbose_name': 'CRM Prospecto',
                'verbose_name_plural': 'CRM Prospectos',
                'ordering': ['-fecha_respuesta'],
            },
        ),
    ]
