# Generated by Django 6.0.5 on 2026-06-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='canal_contacto',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('rrss', 'RRSS'), ('telefono', 'Teléfono'), ('email', 'Email')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='contactado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='fuente',
            field=models.CharField(choices=[('apollo', 'Apollo'), ('manual', 'Manual')], default='apollo', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('email_generado', 'Email generado'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado a Instantly'), ('respondio', 'Respondió'), ('interesado', 'Interesado'), ('no_interesado', 'No interesado'), ('descartado', 'Descartado')], default='pendiente', max_length=30, verbose_name='Estado email'),
        ),
    ]
