# Generated by Django 6.0.5 on 2026-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_prospecto_canal_contactado_fuente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prospecto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='prospecto',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('campana', 'email'), name='unique_campana_email_nonempty'),
        ),
    ]
