# Generated by Django 6.0.5 on 2026-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_prospecto_email_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='estado_respuesta',
            field=models.CharField(choices=[('sin_respuesta', 'Sin respuesta'), ('interesado', 'Interesado ✓'), ('no_interesado', 'No interesado'), ('no_interesado_sap', 'No interesado — usa SAP'), ('no_interesado_sistema', 'No interesado — tiene sistema'), ('pedir_mas_info', 'Pidió más información'), ('agendar_demo', 'Quiere demo'), ('no_responde', 'No responde')], default='sin_respuesta', max_length=30, verbose_name='Estado respuesta'),
        ),
    ]
