# Generated by Django 6.0.5 on 2026-06-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_estado_respuesta_prospecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectocrm',
            name='etapa',
            field=models.CharField(choices=[('respondio', 'Respondió'), ('demo_agendada', 'Demo agendada'), ('demo_hecha', 'Demo hecha'), ('piloto_activo', 'Piloto activo'), ('cliente_pagado', 'Cliente pagado'), ('perdido', 'Perdido')], default='respondio', max_length=30),
        ),
        migrations.AddField(
            model_name='prospectocrm',
            name='fecha_proxima_accion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InteraccionCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='campaigns.prospectocrm')),
            ],
            options={
                'verbose_name': 'Interacción CRM',
                'verbose_name_plural': 'Interacciones CRM',
                'ordering': ['-creado'],
            },
        ),
    ]
