# Generated by Django 6.0.4 on 2026-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_prospectocrm_etapa_prospectocrm_fecha_proxima_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='producto',
            field=models.CharField(choices=[('stockwise', 'StockWise')], max_length=20),
        ),
    ]
